development: &development
  adapter: postgresql
  database: taskbreak_development
  username: postgres
  timeout: 5000
  min_messages: WARNING
  encoding: unicode
  pool: 5

test:
  <<: *development
  database: taskbreak_test
